language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install:
  - python -c "import sys; sys.exit(int(sys.version_info < (3, 2)));" || pip install future
  - pip install coveralls
script:
  - coverage run --source=gostop -m unittest discover tests
after_success:
  - coveralls
